<?php

namespace App\Services\ConsolidatedBilling;

use App\Database\Connection;
use App\Models\ConsolidatedStatement;
use App\Support\Audit\AuditEntry;
use App\Support\Audit\AuditLogger;
use InvalidArgumentException;
use Throwable;

/**
 * Phase 17 / M11 of docs/woms-expansion-plan.md — orchestrates consolidated
 * monthly billing.
 *
 * The two surfaces:
 *
 *   generateForCustomer()   manual + cron entry point. Pulls every eligible
 *                           invoice in the period for one customer and rolls
 *                           them into a single statement.
 *
 *   runMonthlyBatch()       cron entry point. Iterates over every customer
 *                           with monthly_consolidated_billing = 1 and runs
 *                           generateForCustomer() per-customer. Per-customer
 *                           failures are isolated so one bad customer can't
 *                           kill the whole batch.
 */
class ConsolidatedBillingService
{
    public function __construct(
        private readonly Connection $connection,
        private readonly ConsolidatedStatementRepository $statements,
        private readonly AuditLogger $audit,
    ) {
    }

    /**
     * Build (or refresh) a statement for one customer + period.
     *
     * @return array{statement: ConsolidatedStatement, attached: int, eligible_invoice_ids: array<int, int>}
     */
    public function generateForCustomer(
        int $customerId,
        string $periodStart,
        string $periodEnd,
        ?int $actorId = null,
        ?string $notes = null,
    ): array {
        $this->assertValidPeriod($periodStart, $periodEnd);

        $eligible = $this->statements->unconsolidatedInvoiceIdsForCustomer($customerId, $periodStart, $periodEnd);
        $existing = $this->statements->findByPeriod($customerId, $periodStart, $periodEnd);

        // No eligible invoices and no prior statement → no-op (don't create
        // empty headers).
        if ($eligible === [] && $existing === null) {
            throw new InvalidArgumentException(
                "No eligible invoices for customer {$customerId} in {$periodStart}..{$periodEnd}"
            );
        }

        $pdo = $this->connection->pdo();
        $startedTx = false;
        if (!$pdo->inTransaction()) {
            $pdo->beginTransaction();
            $startedTx = true;
        }
        try {
            $statement = $existing
                ?? $this->statements->create($customerId, $periodStart, $periodEnd, $actorId, $notes);

            $attached = $this->statements->attachInvoices($statement->id, $eligible);
            $statement = $this->statements->recomputeTotals($statement->id);

            $this->audit->log(new AuditEntry(
                $existing === null ? 'consolidated_statement.created' : 'consolidated_statement.refreshed',
                'consolidated_statement',
                (string) $statement->id,
                $actorId,
                [
                    'customer_id' => $customerId,
                    'period_start' => $periodStart,
                    'period_end' => $periodEnd,
                    'attached_invoice_count' => $attached,
                    'eligible_invoice_count' => count($eligible),
                ]
            ));

            if ($startedTx) {
                $pdo->commit();
            }
            return [
                'statement' => $statement,
                'attached' => $attached,
                'eligible_invoice_ids' => $eligible,
            ];
        } catch (Throwable $e) {
            if ($startedTx && $pdo->inTransaction()) {
                $pdo->rollBack();
            }
            throw $e;
        }
    }

    /**
     * Cron entry. For every opted-in customer who has unconsolidated invoices
     * in the period, generate a statement.
     *
     * @return array{processed: int, failures: array<int, array{customer_id: int, error: string}>}
     */
    public function runMonthlyBatch(string $periodStart, string $periodEnd, ?int $actorId = null): array
    {
        $this->assertValidPeriod($periodStart, $periodEnd);
        $customerIds = $this->statements->eligibleCustomerIds($periodStart, $periodEnd);
        $processed = 0;
        $failures = [];
        foreach ($customerIds as $customerId) {
            try {
                $this->generateForCustomer($customerId, $periodStart, $periodEnd, $actorId, 'auto-generated by monthly batch');
                $processed++;
            } catch (Throwable $e) {
                $failures[] = ['customer_id' => $customerId, 'error' => $e->getMessage()];
                $this->audit->log(new AuditEntry(
                    'consolidated_statement.batch_failure',
                    'customer',
                    (string) $customerId,
                    $actorId,
                    ['period_start' => $periodStart, 'period_end' => $periodEnd, 'error' => $e->getMessage()]
                ));
            }
        }
        return ['processed' => $processed, 'failures' => $failures];
    }

    public function detachInvoice(int $statementId, int $invoiceId, ?int $actorId = null): ConsolidatedStatement
    {
        $statement = $this->statements->findById($statementId);
        if ($statement === null) {
            throw new InvalidArgumentException("statement {$statementId} not found");
        }
        $this->statements->detachInvoice($statementId, $invoiceId);
        $statement = $this->statements->recomputeTotals($statementId);
        $this->audit->log(new AuditEntry(
            'consolidated_statement.invoice_detached',
            'consolidated_statement',
            (string) $statementId,
            $actorId,
            ['invoice_id' => $invoiceId]
        ));
        return $statement;
    }

    public function markSent(int $statementId, ?int $actorId = null): ConsolidatedStatement
    {
        $statement = $this->statements->markSent($statementId);
        $this->audit->log(new AuditEntry(
            'consolidated_statement.sent',
            'consolidated_statement',
            (string) $statementId,
            $actorId,
            null
        ));
        return $statement;
    }

    public function cancel(int $statementId, ?int $actorId = null): ConsolidatedStatement
    {
        $statement = $this->statements->cancel($statementId);
        $this->audit->log(new AuditEntry(
            'consolidated_statement.cancelled',
            'consolidated_statement',
            (string) $statementId,
            $actorId,
            null
        ));
        return $statement;
    }

    private function assertValidPeriod(string $periodStart, string $periodEnd): void
    {
        $ts1 = strtotime($periodStart);
        $ts2 = strtotime($periodEnd);
        if (!$ts1 || !$ts2) {
            throw new InvalidArgumentException('period_start and period_end must be valid dates');
        }
        if ($ts1 > $ts2) {
            throw new InvalidArgumentException('period_start must be <= period_end');
        }
    }
}
