CREATE TABLE IF NOT EXISTS payment_webhook_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    provider VARCHAR(40) NOT NULL,
    provider_event_id VARCHAR(191) NULL,
    dedupe_key VARCHAR(191) NOT NULL,
    event_type VARCHAR(120) NOT NULL,
    invoice_id INT UNSIGNED NULL,
    transaction_id VARCHAR(191) NULL,
    refund_id VARCHAR(191) NULL,
    payment_id VARCHAR(191) NULL,
    session_id VARCHAR(191) NULL,
    order_id VARCHAR(191) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'unmatched',
    payload JSON NOT NULL,
    attempts INT UNSIGNED NOT NULL DEFAULT 1,
    matched_at TIMESTAMP NULL,
    processed_at TIMESTAMP NULL,
    recovered_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_payment_webhook_events_dedupe (dedupe_key),
    INDEX idx_payment_webhook_events_provider_status (provider, status),
    INDEX idx_payment_webhook_events_invoice (invoice_id),
    INDEX idx_payment_webhook_events_provider_event (provider, provider_event_id),
    CONSTRAINT fk_payment_webhook_events_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
