<?php

return [
    'defaults' => [
        'shop.name' => [
            'group' => 'profile',
            'type' => 'string',
            'description' => 'Display name used across invoices, estimates, and the customer portal.',
            'value' => null,
        ],
        'shop.email' => [
            'group' => 'profile',
            'type' => 'string',
            'description' => 'Primary contact email for notifications and document headers.',
            'value' => null,
        ],
        'shop.phone' => [
            'group' => 'profile',
            'type' => 'string',
            'description' => 'Primary phone number rendered on outbound documents.',
            'value' => null,
        ],
        'shop.logo_url' => [
            'group' => 'profile',
            'type' => 'string',
            'description' => 'Public URL for the shop logo used on estimates, invoices, and portal pages.',
            'value' => null,
        ],
        'shop.address' => [
            'group' => 'profile',
            'type' => 'json',
            'description' => 'Address payload containing street, city, state, postal code, and country.',
            'value' => [
                'street' => null,
                'city' => null,
                'state' => null,
                'postal_code' => null,
                'country' => null,
            ],
        ],
        'pricing.tax_rate' => [
            'group' => 'pricing',
            'type' => 'float',
            'description' => 'Default sales tax percentage applied to taxable line items.',
            'value' => 0.0,
        ],
        'pricing.labor_rate' => [
            'group' => 'pricing',
            'type' => 'float',
            'description' => 'Default hourly labor rate applied when creating estimate labor lines.',
            'value' => 0.0,
        ],
        'pricing.call_out_fee' => [
            'group' => 'pricing',
            'type' => 'float',
            'description' => 'Default call-out or mobile service fee.',
            'value' => 0.0,
        ],
        'pricing.mileage_rate' => [
            'group' => 'pricing',
            'type' => 'float',
            'description' => 'Mileage charge per unit used for mobile appointments.',
            'value' => 0.0,
        ],
        'integrations.stripe.public_key' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Stripe publishable API key used for payment forms.',
            'value' => null,
        ],
        'integrations.stripe.secret_key' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Stripe secret API key used for server-side payment actions.',
            'value' => null,
        ],
        'integrations.stripe.webhook_secret' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Stripe webhook signing secret for verifying incoming payment events.',
            'value' => null,
        ],
        'integrations.square.token' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Square access token for payments and catalog sync.',
            'value' => null,
        ],
        'integrations.square.webhook_signature_key' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Square webhook signature key for validating notifications.',
            'value' => null,
        ],
        'integrations.paypal.client_id' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'PayPal client ID for web checkout flows.',
            'value' => null,
        ],
        'integrations.paypal.client_secret' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'PayPal client secret for token exchange.',
            'value' => null,
        ],
        'integrations.paypal.webhook_id' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'PayPal webhook ID used to validate incoming payment webhooks.',
            'value' => null,
        ],
        'integrations.zoho.client_id' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Zoho CRM client ID for syncing customer or invoice records.',
            'value' => null,
        ],
        'integrations.zoho.client_secret' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Zoho CRM client secret for token exchange.',
            'value' => null,
        ],
        'integrations.zoho.refresh_token' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Zoho CRM refresh token used to rotate access tokens.',
            'value' => null,
        ],
        'integrations.zoho.org_id' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Zoho CRM organization ID for API requests.',
            'value' => null,
        ],
        'notifications.mail.from_name' => [
            'group' => 'notifications',
            'type' => 'string',
            'description' => 'Default email from-name for transactional emails.',
            'value' => null,
        ],
        'notifications.mail.from_address' => [
            'group' => 'notifications',
            'type' => 'string',
            'description' => 'Default email from-address for transactional emails.',
            'value' => null,
        ],
        'notifications.sms.from_number' => [
            'group' => 'notifications',
            'type' => 'string',
            'description' => 'SMS sender number for appointment, estimate, and invoice messages.',
            'value' => null,
        ],
        'integrations.twilio.sid' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Twilio Account SID for SMS dispatch.',
            'value' => null,
        ],
        'integrations.twilio.token' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Twilio auth token for SMS dispatch.',
            'value' => null,
        ],
        'integrations.smtp.host' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'SMTP host name for outbound email.',
            'value' => null,
        ],
        'integrations.smtp.port' => [
            'group' => 'integrations',
            'type' => 'integer',
            'description' => 'SMTP port for outbound email.',
            'value' => 587,
        ],
        'integrations.smtp.username' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'SMTP username for authentication.',
            'value' => null,
        ],
        'integrations.smtp.password' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'SMTP password or token for authentication.',
            'value' => null,
        ],
        'integrations.smtp.encryption' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'SMTP encryption protocol (tls/ssl/none).',
            'value' => 'tls',
        ],
        'integrations.recaptcha.site_key' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'reCAPTCHA site key for public forms.',
            'value' => null,
        ],
        'integrations.recaptcha.secret_key' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'reCAPTCHA secret key for server-side verification.',
            'value' => null,
        ],
        'integrations.recaptcha.enabled' => [
            'group' => 'integrations',
            'type' => 'boolean',
            'description' => 'Enable reCAPTCHA verification for public forms and authentication flows.',
            'value' => false,
        ],
        'integrations.recaptcha.score_threshold' => [
            'group' => 'integrations',
            'type' => 'float',
            'description' => 'Minimum acceptable reCAPTCHA score (0.0 - 1.0) before processing public forms.',
            'value' => 0.5,
        ],
        'integrations.partstech.api_base' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Base URL for PartsTech API requests.',
            'value' => 'https://api.partstech.com',
        ],
        'integrations.partstech.api_key' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'PartsTech API key used for VIN decoding and catalog search.',
            'value' => null,
        ],
        'integrations.partstech.markup_tiers' => [
            'group' => 'integrations',
            'type' => 'json',
            'description' => 'Optional pricing markup tiers applied to PartsTech catalog results.',
            'value' => [],
        ],
        'payments.urls.success' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Redirect URL after successful online payment.',
            'value' => env('APP_URL', 'http://localhost') . '/payment/success',
        ],
        'payments.urls.cancel' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Redirect URL when a payer cancels checkout.',
            'value' => env('APP_URL', 'http://localhost') . '/payment/cancel',
        ],
        'documents.terms.estimates' => [
            'group' => 'documents',
            'type' => 'string',
            'description' => 'Terms and conditions block rendered on estimates.',
            'value' => null,
        ],
        'documents.terms.invoices' => [
            'group' => 'documents',
            'type' => 'string',
            'description' => 'Terms and conditions block rendered on invoices.',
            'value' => null,
        ],
    ],
];
