<?php

return [
    'defaults' => [
        'shop.name' => [
            'group' => 'profile',
            'type' => 'string',
            'description' => 'Display name used across invoices, estimates, and the customer portal.',
            'value' => null,
        ],
        'shop.email' => [
            'group' => 'profile',
            'type' => 'string',
            'description' => 'Primary contact email for notifications and document headers.',
            'value' => null,
        ],
        'shop.phone' => [
            'group' => 'profile',
            'type' => 'string',
            'description' => 'Primary phone number rendered on outbound documents.',
            'value' => null,
        ],
        'shop.address' => [
            'group' => 'profile',
            'type' => 'json',
            'description' => 'Address payload containing street, city, state, postal code, and country.',
            'value' => [
                'street' => null,
                'city' => null,
                'state' => null,
                'postal_code' => null,
                'country' => null,
            ],
        ],
        'pricing.tax_rate' => [
            'group' => 'pricing',
            'type' => 'float',
            'description' => 'Default sales tax percentage applied to taxable line items.',
            'value' => 0.0,
        ],
        'pricing.labor_rate' => [
            'group' => 'pricing',
            'type' => 'float',
            'description' => 'Default hourly labor rate applied when creating estimate labor lines.',
            'value' => 0.0,
        ],
        'pricing.call_out_fee' => [
            'group' => 'pricing',
            'type' => 'float',
            'description' => 'Default call-out or mobile service fee.',
            'value' => 0.0,
        ],
        'pricing.mileage_rate' => [
            'group' => 'pricing',
            'type' => 'float',
            'description' => 'Mileage charge per unit used for mobile appointments.',
            'value' => 0.0,
        ],
        'integrations.stripe.public_key' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Stripe publishable API key used for payment forms.',
            'value' => null,
        ],
        'integrations.stripe.secret_key' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Stripe secret API key used for server-side payment actions.',
            'value' => null,
        ],
        'integrations.square.token' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Square access token for payments and catalog sync.',
            'value' => null,
        ],
        'integrations.paypal.client_id' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'PayPal client ID for web checkout flows.',
            'value' => null,
        ],
        'integrations.paypal.client_secret' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'PayPal client secret for token exchange.',
            'value' => null,
        ],
        'notifications.mail.from_name' => [
            'group' => 'notifications',
            'type' => 'string',
            'description' => 'Default email from-name for transactional emails.',
            'value' => null,
        ],
        'notifications.mail.from_address' => [
            'group' => 'notifications',
            'type' => 'string',
            'description' => 'Default email from-address for transactional emails.',
            'value' => null,
        ],
        'notifications.sms.from_number' => [
            'group' => 'notifications',
            'type' => 'string',
            'description' => 'SMS sender number for appointment, estimate, and invoice messages.',
            'value' => null,
        ],
        'integrations.twilio.sid' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Twilio Account SID for SMS dispatch.',
            'value' => null,
        ],
        'integrations.twilio.token' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Twilio auth token for SMS dispatch.',
            'value' => null,
        ],
        'integrations.smtp.host' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'SMTP host name for outbound email.',
            'value' => null,
        ],
        'integrations.smtp.port' => [
            'group' => 'integrations',
            'type' => 'integer',
            'description' => 'SMTP port for outbound email.',
            'value' => 587,
        ],
        'integrations.smtp.username' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'SMTP username for authentication.',
            'value' => null,
        ],
        'integrations.smtp.password' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'SMTP password or token for authentication.',
            'value' => null,
        ],
        'integrations.smtp.encryption' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'SMTP encryption protocol (tls/ssl/none).',
            'value' => 'tls',
        ],
        'integrations.recaptcha.site_key' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'reCAPTCHA site key for public forms.',
            'value' => null,
        ],
        'integrations.recaptcha.secret_key' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'reCAPTCHA secret key for server-side verification.',
            'value' => null,
        ],
        'integrations.partstech.api_base' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'Base URL for PartsTech API requests.',
            'value' => 'https://api.partstech.com',
        ],
        'integrations.partstech.api_key' => [
            'group' => 'integrations',
            'type' => 'string',
            'description' => 'PartsTech API key used for VIN decoding and catalog search.',
            'value' => null,
        ],
        'integrations.partstech.markup_tiers' => [
            'group' => 'integrations',
            'type' => 'json',
            'description' => 'Optional pricing markup tiers applied to PartsTech catalog results.',
            'value' => [],
        ],
        'documents.terms.estimates' => [
            'group' => 'documents',
            'type' => 'string',
            'description' => 'Terms and conditions block rendered on estimates.',
            'value' => null,
        ],
        'documents.terms.invoices' => [
            'group' => 'documents',
            'type' => 'string',
            'description' => 'Terms and conditions block rendered on invoices.',
            'value' => null,
        ],
    ],
];
